name: ninja_pem
description: Dart library that provides simple and elegant way to decode and encode PEM.
version: 2.0.2
homepage: https://github.com/ninja-dart/pem

documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.22.2
